name: CI

on:
  issues:
    types: [opened]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Debug
      run: echo "${{ toJson(github) }}"
    - name: Run a one-line script
      run: "${{ secrets.SECRET_SAUCE }} '${{ toJson(github.event.issue) }}'"
#      run: 'curl -XPOST -u "${{ secrets.SECRET_ORG }}:${{ secrets.API }}" -H "Accept: application/vnd.github.everest-preview+json"  -H "Content-Type: application/json" ${{ secrets.SOMEWHERE_SECRET}} --data ${{ secrets.GENERIC_JSON }} '


